import { Container, Center, SlideFade, Heading, SimpleGrid, Box, Text, Button } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

import Papa from "papaparse";

import BasicEditableTextCard from "../components/BasicEditableTextCard";
import CsvImporter from "../components/CsvImporter";

export default function Home() {
  //Top Level JSON object of CSV data
  const [parentJson, setParentJson] = useState([]);
  //Toggle for the CSV Importer
  const [showImporter, setShowImporter] = useState(true);

  const onEdit = (key, value) => {
    //Create deep copy of parentJson
    let prevParentJson = [...parentJson];
    //Update the value of the keys
    prevParentJson[key] = { ...prevParentJson[key], name: value };
    //Set the state of the parentJson
    setParentJson(prevParentJson);
  };

  const exportCsv = async () => {
    //Export JSON to CSV & Download CSV
    const csv = Papa.unparse(parentJson);
    const blob = new Blob([csv], { type: "text/csv" });
    const href = await URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = href;
    link.download = "myFile.csv";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    console.log(csv, "csv");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CSV Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxW={"60%"} minH="40vh">
          <Center mb={4}>
            {Object.keys(parentJson).length > 0 ? (
              <>
                <Text fontSize={"2xl"} mr={6}>
                  Ready to export?{"   "}
                </Text>
                <Button
                  onClick={() => {
                    exportCsv();
                  }}
                >
                  Export CSV
                </Button>
              </>
            ) : (
              <Heading>Upload CSV</Heading>
            )}
          </Center>
          {showImporter && (
            <SlideFade in={showImporter} hidden={!showImporter} offsetY="-10px">
              <CsvImporter parentJson={parentJson} setParentJson={setParentJson} setShowImporter={setShowImporter} />
            </SlideFade>
          )}
          <SimpleGrid columns={2} spacingX="40px" spacingY="20px">
            {Object.keys(parentJson).length > 0 && (
              <Box minH="80px">
                <pre>{JSON.stringify(parentJson, null, 2)}</pre>
              </Box>
            )}
            <Box minH="80px">
              {Object.keys(parentJson).length > 0 &&
                Object.keys(parentJson).map((itemKey) => {
                  return (
                    <Container key={itemKey}>
                      <Text m={0} mt={10} p={0}>
                        {itemKey}
                      </Text>
                      <BasicEditableTextCard csvKey={itemKey} text={parentJson[itemKey].name} onEdit={onEdit} />
                    </Container>
                  );
                })}
            </Box>
          </SimpleGrid>
        </Container>
      </main>
    </div>
  );
}
