import { Container, Center, SlideFade, Heading, SimpleGrid, Box } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

import BasicEditableTextCard from "../components/BasicEditableTextCard";
import CsvImporter from "../components/CsvImporter";

export default function Home() {
  //Top Level JSON object of CSV data
  const [parentJson, setParentJson] = useState({});
  //Toggle for the CSV Importer
  const [showImporter, setShowImporter] = useState(true);

  const onEdit = (key, value) => {
    console.log("onEdit", key, value);
    setParentJson((prev) => {
      return { ...prev, [key]: { ...prev[key], name: value } };
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxW={"60%"} minH="40vh">
          <Center mb={4}>
            <Heading>Upload CSV</Heading>
          </Center>
          {showImporter && (
            <SlideFade in={showImporter} hidden={!showImporter} offsetY="-10px">
              <CsvImporter parentJson={parentJson} setParentJson={setParentJson} setShowImporter={setShowImporter} />
            </SlideFade>
          )}
          <SimpleGrid columns={2} spacingX="40px" spacingY="20px">
            {Object.keys(parentJson).length > 0 && (
              <Box minH="80px">
                <pre>{JSON.stringify(parentJson, null, 2)}</pre>
              </Box>
            )}
            <Box minH="80px">
              {parentJson &&
                Object.keys(parentJson).length > 0 &&
                Object.keys(parentJson).map((itemKey) => {
                  return (
                    <Container key={itemKey}>
                      <BasicEditableTextCard csvKey={itemKey} text={parentJson[itemKey].name} onEdit={onEdit} />
                    </Container>
                  );
                })}
            </Box>
          </SimpleGrid>
        </Container>
      </main>
    </div>
  );
}
